/**
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/25/2016
 */

var DateDescriptorEnum = {

    //TODO: Write general description for this element
    LAST_WEEK : "lastWeek",

    //TODO: Write general description for this element
    NEXT_WEEK : "nextWeek",

    //TODO: Write general description for this element
    THIS_MONTH : "thisMonth",

    //TODO: Write general description for this element
    THIS_WEEK : "thisWeek"

};

module.exports = DateDescriptorEnum;