/**
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/25/2016
 */

var FormatTypeEnum = {

    //TODO: Write general description for this element
    COLLECTION : "collection",

    //TODO: Write general description for this element
    COMIC : "comic"

};

module.exports = FormatTypeEnum;