/**
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/25/2016
 */

var configuration = {
    //The base Uri for API calls
    BASEURI : "http://gateway.marvel.com/v1/public",

    //TODO: Replace the Referer with an appropriate value
    referer : "TODO: Replace",

    apikey : ""

};

module.exports = configuration;

