/**
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/25/2016
 */

var _request = require('../Http/Client/RequestClient'),
    _configuration = require('../configuration'),
    _APIHelper = require('../APIHelper');

var ComicsController = {

    /**
     * Fetches a single comic by id.
     * @param {string} comicId    Required parameter: A single comic.
     * @param {function} callback    Required parameter: Callback function in the form of function(error, response)
     *
     * @return {Comic}
     */
    getComicIndividual : function(comicId, callback){

        //prepare query string for API call;
        var _baseUri = _configuration.BASEURI;
        
        var _queryBuilder = _baseUri + "/comics/{comicId}";
        
        //Process template parameters
        _queryBuilder = _APIHelper.appendUrlWithTemplateParameters(_queryBuilder, {
            "comicId" : comicId
        });

        //Process query parameters
        _queryBuilder = _APIHelper.appendUrlWithQueryParameters(_queryBuilder, {
            "apikey" : _configuration.apikey
        });

        //validate and preprocess url
        var _queryUrl = _APIHelper.cleanUrl(_queryBuilder);
        
        //prepare headers
        var _headers = {
            "accept" : "application/json",
            "referer" : _configuration.referer
        };

        //Construct the request
        var _options = {
            queryUrl: _queryUrl,
            method: "GET",
            headers: _headers,
        };
        
        //Build the response processing. 
        function cb(_error, _response, _context) {
            if(_error) {
                callback({errorMessage: _error.message, errorCode: _error.code},null,_context);
            } else if (_response.statusCode >= 200 && _response.statusCode <= 206) {
                callback(null,JSON.parse(_response.body),_context);
            } else if (_response.statusCode == 404) {
                callback({errorMessage: "Comic not found.", errorCode: 404, errorResponse:_response.body},null,_context);
            } else {
                callback({errorMessage: "HTTP Response Not OK", errorCode: _response.statusCode, errorResponse:_response.body},null,_context);
            }
        }
        _request(_options, cb);
    },


    /**
     * Fetches lists of characters filtered by a comic id.
     * @param {string} comicId    Required parameter: A single comic.
     * @param {string|null} events    Optional parameter: Return only characters which appear comics that took place in the specified events (accepts a comma-separated list of ids).
     * @param {string|null} limit    Optional parameter: Limit the result set to the specified number of resources.
     * @param {string|null} modifiedSince    Optional parameter: Return only characters which have been modified since the specified date.
     * @param {string|null} name    Optional parameter: Return only characters matching the specified full character name (e.g. Spider-Man).
     * @param {string|null} nameStartsWith    Optional parameter: Return characters with names that begin with the specified string (e.g. Sp).
     * @param {string|null} offset    Optional parameter: Skip the specified number of resources in the result set.
     * @param {string|null} orderBy    Optional parameter: Order the result set by a field or fields. Add a "-" to the value sort in descending order. Multiple values are given priority in the order in which they are passed. (Acceptable values are: "name", "modified", "-name", "-modified")
     * @param {string|null} series    Optional parameter: Return only characters which appear the specified series (accepts a comma-separated list of ids).
     * @param {string|null} stories    Optional parameter: Return only characters which appear the specified stories (accepts a comma-separated list of ids).
     * @param {function} callback    Required parameter: Callback function in the form of function(error, response)
     *
     * @return {CharacterDataWrapper}
     */
    getComicCharacterCollection : function(comicId, events, limit, modifiedSince, name, nameStartsWith, offset, orderBy, series, stories, callback){

        //prepare query string for API call;
        var _baseUri = _configuration.BASEURI;
        
        var _queryBuilder = _baseUri + "/comics/{comicId}/characters";
        
        //Process template parameters
        _queryBuilder = _APIHelper.appendUrlWithTemplateParameters(_queryBuilder, {
            "comicId" : comicId
        });

        //Process query parameters
        _queryBuilder = _APIHelper.appendUrlWithQueryParameters(_queryBuilder, {
            "events" : events,
            "limit" : limit,
            "modifiedSince" : modifiedSince,
            "name" : name,
            "nameStartsWith" : nameStartsWith,
            "offset" : offset,
            "orderBy" : orderBy,
            "series" : series,
            "stories" : stories,
            "apikey" : _configuration.apikey
        });

        //validate and preprocess url
        var _queryUrl = _APIHelper.cleanUrl(_queryBuilder);
        
        //prepare headers
        var _headers = {
            "accept" : "application/json",
            "referer" : _configuration.referer
        };

        //Construct the request
        var _options = {
            queryUrl: _queryUrl,
            method: "GET",
            headers: _headers,
        };
        
        //Build the response processing. 
        function cb(_error, _response, _context) {
            if(_error) {
                callback({errorMessage: _error.message, errorCode: _error.code},null,_context);
            } else if (_response.statusCode >= 200 && _response.statusCode <= 206) {
                callback(null,JSON.parse(_response.body),_context);
            } else if (_response.statusCode == 409) {
                callback({errorMessage: "Limit greater than 100.", errorCode: 409, errorResponse:_response.body},null,_context);
            } else {
                callback({errorMessage: "HTTP Response Not OK", errorCode: _response.statusCode, errorResponse:_response.body},null,_context);
            }
        }
        _request(_options, cb);
    },


    /**
     * Fetches lists of creators filtered by a comic id.
     * @param {string} comicId    Required parameter: A single comic.
     * @param {string|null} comics    Optional parameter: Return only creators who worked on in the specified comics (accepts a comma-separated list of ids).
     * @param {string|null} firstName    Optional parameter: Filter by creator first name (e.g. brian).
     * @param {string|null} firstNameStartsWith    Optional parameter: Filter by creator first names that match critera (e.g. B, St L).
     * @param {string|null} lastName    Optional parameter: Filter by creator last name (e.g. Bendis).
     * @param {string|null} lastNameStartsWith    Optional parameter: Filter by creator last names that match critera (e.g. Ben).
     * @param {string|null} limit    Optional parameter: Limit the result set to the specified number of resources.
     * @param {string|null} middleName    Optional parameter: Filter by creator middle name (e.g. Michael).
     * @param {string|null} middleNameStartsWith    Optional parameter: Filter by creator middle names that match critera (e.g. Mi).
     * @param {string|null} modifiedSince    Optional parameter: Return only creators which have been modified since the specified date.
     * @param {string|null} nameStartsWith    Optional parameter: Filter by creator names that match critera (e.g. B, St L).
     * @param {string|null} offset    Optional parameter: Skip the specified number of resources in the result set.
     * @param {string|null} orderBy    Optional parameter: Order the result set by a field or fields. Add a "-" to the value sort in descending order. Multiple values are given priority in the order in which they are passed. (Acceptable values are: "lastName", "firstName", "middleName", "suffix", "modified", "-lastName", "-firstName", "-middleName", "-suffix", "-modified")
     * @param {string|null} series    Optional parameter: Return only creators who worked on the specified series (accepts a comma-separated list of ids).
     * @param {string|null} stories    Optional parameter: Return only creators who worked on the specified stories (accepts a comma-separated list of ids).
     * @param {string|null} suffix    Optional parameter: Filter by suffix or honorific (e.g. Jr., Sr.).
     * @param {function} callback    Required parameter: Callback function in the form of function(error, response)
     *
     * @return {CreatorDataWrapper}
     */
    getCreatorCollectionByComicId : function(comicId, comics, firstName, firstNameStartsWith, lastName, lastNameStartsWith, limit, middleName, middleNameStartsWith, modifiedSince, nameStartsWith, offset, orderBy, series, stories, suffix, callback){

        //prepare query string for API call;
        var _baseUri = _configuration.BASEURI;
        
        var _queryBuilder = _baseUri + "/comics/{comicId}/creators";
        
        //Process template parameters
        _queryBuilder = _APIHelper.appendUrlWithTemplateParameters(_queryBuilder, {
            "comicId" : comicId
        });

        //Process query parameters
        _queryBuilder = _APIHelper.appendUrlWithQueryParameters(_queryBuilder, {
            "comics" : comics,
            "firstName" : firstName,
            "firstNameStartsWith" : firstNameStartsWith,
            "lastName" : lastName,
            "lastNameStartsWith" : lastNameStartsWith,
            "limit" : limit,
            "middleName" : middleName,
            "middleNameStartsWith" : middleNameStartsWith,
            "modifiedSince" : modifiedSince,
            "nameStartsWith" : nameStartsWith,
            "offset" : offset,
            "orderBy" : orderBy,
            "series" : series,
            "stories" : stories,
            "suffix" : suffix,
            "apikey" : _configuration.apikey
        });

        //validate and preprocess url
        var _queryUrl = _APIHelper.cleanUrl(_queryBuilder);
        
        //prepare headers
        var _headers = {
            "accept" : "application/json",
            "referer" : _configuration.referer
        };

        //Construct the request
        var _options = {
            queryUrl: _queryUrl,
            method: "GET",
            headers: _headers,
        };
        
        //Build the response processing. 
        function cb(_error, _response, _context) {
            if(_error) {
                callback({errorMessage: _error.message, errorCode: _error.code},null,_context);
            } else if (_response.statusCode >= 200 && _response.statusCode <= 206) {
                callback(null,JSON.parse(_response.body),_context);
            } else if (_response.statusCode == 409) {
                callback({errorMessage: "Limit greater than 100.", errorCode: 409, errorResponse:_response.body},null,_context);
            } else {
                callback({errorMessage: "HTTP Response Not OK", errorCode: _response.statusCode, errorResponse:_response.body},null,_context);
            }
        }
        _request(_options, cb);
    },


    /**
     * Fetches lists of events filtered by a comic id.
     * @param {string} comicId    Required parameter: A single comic.
     * @param {string|null} characters    Optional parameter: Return only events which feature the specified characters (accepts a comma-separated list of ids).
     * @param {string|null} creators    Optional parameter: Return only events which feature work by the specified creators (accepts a comma-separated list of ids).
     * @param {string|null} limit    Optional parameter: Limit the result set to the specified number of resources.
     * @param {string|null} modifiedSince    Optional parameter: Return only events which have been modified since the specified date.
     * @param {string|null} name    Optional parameter: Filter the event list by name.
     * @param {string|null} nameStartsWith    Optional parameter: Return events with names that begin with the specified string (e.g. Sp).
     * @param {string|null} offset    Optional parameter: Skip the specified number of resources in the result set.
     * @param {string|null} orderBy    Optional parameter: Order the result set by a field or fields. Add a "-" to the value sort in descending order. Multiple values are given priority in the order in which they are passed. (Acceptable values are: "name", "startDate", "modified", "-name", "-startDate", "-modified")
     * @param {string|null} series    Optional parameter: Return only events which are part of the specified series (accepts a comma-separated list of ids).
     * @param {string|null} stories    Optional parameter: Return only events which contain the specified stories (accepts a comma-separated list of ids).
     * @param {function} callback    Required parameter: Callback function in the form of function(error, response)
     *
     * @return {EventDataWrapper}
     */
    getIssueEventsCollection : function(comicId, characters, creators, limit, modifiedSince, name, nameStartsWith, offset, orderBy, series, stories, callback){

        //prepare query string for API call;
        var _baseUri = _configuration.BASEURI;
        
        var _queryBuilder = _baseUri + "/comics/{comicId}/events";
        
        //Process template parameters
        _queryBuilder = _APIHelper.appendUrlWithTemplateParameters(_queryBuilder, {
            "comicId" : comicId
        });

        //Process query parameters
        _queryBuilder = _APIHelper.appendUrlWithQueryParameters(_queryBuilder, {
            "characters" : characters,
            "creators" : creators,
            "limit" : limit,
            "modifiedSince" : modifiedSince,
            "name" : name,
            "nameStartsWith" : nameStartsWith,
            "offset" : offset,
            "orderBy" : orderBy,
            "series" : series,
            "stories" : stories,
            "apikey" : _configuration.apikey
        });

        //validate and preprocess url
        var _queryUrl = _APIHelper.cleanUrl(_queryBuilder);
        
        //prepare headers
        var _headers = {
            "accept" : "application/json",
            "referer" : _configuration.referer
        };

        //Construct the request
        var _options = {
            queryUrl: _queryUrl,
            method: "GET",
            headers: _headers,
        };
        
        //Build the response processing. 
        function cb(_error, _response, _context) {
            if(_error) {
                callback({errorMessage: _error.message, errorCode: _error.code},null,_context);
            } else if (_response.statusCode >= 200 && _response.statusCode <= 206) {
                callback(null,JSON.parse(_response.body),_context);
            } else if (_response.statusCode == 409) {
                callback({errorMessage: "Limit greater than 100.", errorCode: 409, errorResponse:_response.body},null,_context);
            } else {
                callback({errorMessage: "HTTP Response Not OK", errorCode: _response.statusCode, errorResponse:_response.body},null,_context);
            }
        }
        _request(_options, cb);
    },


    /**
     * Fetches lists of stories filtered by a comic id.
     * @param {string} comicId    Required parameter: A single comic.
     * @param {string|null} characters    Optional parameter: Return only stories which feature the specified characters (accepts a comma-separated list of ids).
     * @param {string|null} creators    Optional parameter: Return only stories which feature work by the specified creators (accepts a comma-separated list of ids).
     * @param {string|null} events    Optional parameter: Return only stories which take place during the specified events (accepts a comma-separated list of ids).
     * @param {string|null} limit    Optional parameter: Limit the result set to the specified number of resources.
     * @param {string|null} modifiedSince    Optional parameter: Return only stories which have been modified since the specified date.
     * @param {string|null} offset    Optional parameter: Skip the specified number of resources.
     * @param {string|null} orderBy    Optional parameter: Order the result set by a field or fields. Add a "-" to the value sort in descending order. Multiple values are given priority in the order in which they are passed. (Acceptable values are: "id", "modified", "-id", "-modified")
     * @param {string|null} series    Optional parameter: Return only stories contained the specified series (accepts a comma-separated list of ids).
     * @param {function} callback    Required parameter: Callback function in the form of function(error, response)
     *
     * @return {StoryDataWrapper}
     */
    getComicStoryCollectionByComicId : function(comicId, characters, creators, events, limit, modifiedSince, offset, orderBy, series, callback){

        //prepare query string for API call;
        var _baseUri = _configuration.BASEURI;
        
        var _queryBuilder = _baseUri + "/comics/{comicId}/stories";
        
        //Process template parameters
        _queryBuilder = _APIHelper.appendUrlWithTemplateParameters(_queryBuilder, {
            "comicId" : comicId
        });

        //Process query parameters
        _queryBuilder = _APIHelper.appendUrlWithQueryParameters(_queryBuilder, {
            "characters" : characters,
            "creators" : creators,
            "events" : events,
            "limit" : limit,
            "modifiedSince" : modifiedSince,
            "offset" : offset,
            "orderBy" : orderBy,
            "series" : series,
            "apikey" : _configuration.apikey
        });

        //validate and preprocess url
        var _queryUrl = _APIHelper.cleanUrl(_queryBuilder);
        
        //prepare headers
        var _headers = {
            "accept" : "application/json",
            "referer" : _configuration.referer
        };

        //Construct the request
        var _options = {
            queryUrl: _queryUrl,
            method: "GET",
            headers: _headers,
        };
        
        //Build the response processing. 
        function cb(_error, _response, _context) {
            if(_error) {
                callback({errorMessage: _error.message, errorCode: _error.code},null,_context);
            } else if (_response.statusCode >= 200 && _response.statusCode <= 206) {
                callback(null,JSON.parse(_response.body),_context);
            } else if (_response.statusCode == 409) {
                callback({errorMessage: "Limit greater than 100.", errorCode: 409, errorResponse:_response.body},null,_context);
            } else {
                callback({errorMessage: "HTTP Response Not OK", errorCode: _response.statusCode, errorResponse:_response.body},null,_context);
            }
        }
        _request(_options, cb);
    },


    /**
     * Fetches lists of comics.
     * @param {string|null} characters    Optional parameter: Return only comics which feature the specified characters (accepts a comma-separated list of ids).
     * @param {string|null} collaborators    Optional parameter: Return only comics in which the specified creators worked together (for example in which BOTH Stan Lee and Jack Kirby did work). Accepts a comma-separated list of ids.
     * @param {string|null} creators    Optional parameter: Return only comics which feature work by the specified creators (accepts a comma-separated list of ids).
     * @param {DateDescriptorEnum|null} dateDescriptor    Optional parameter: Return comics within a predefined date range.
     * @param {string|null} dateRange    Optional parameter: Return comics within a predefined date range.  Dates must be specified as date1,date2 (e.g. 2013-01-01,2013-01-02).  Dates are preferably formatted as YYYY-MM-DD but may be sent as any common date format.
     * @param {string|null} diamondCode    Optional parameter: Filter by diamond code.
     * @param {string|null} digitalId    Optional parameter: Filter by digital comic id.
     * @param {string|null} ean    Optional parameter: Filter by EAN.
     * @param {string|null} events    Optional parameter: Return only comics which take place in the specified events (accepts a comma-separated list of ids).
     * @param {string|null} format    Optional parameter: Filter by the issue format (e.g. comic, digital comic, hardcover). (Acceptable values are: "comic", "magazine", "trade paperback", "hardcover", "digest", "graphic novel", "digital comic", "infinite comic")
     * @param {FormatTypeEnum|null} formatType    Optional parameter: Filter by the issue format type (comic or collection).
     * @param {string|null} hasDigitalIssue    Optional parameter: Include only results which are available digitally. (Acceptable values are: "true")
     * @param {string|null} isbn    Optional parameter: Filter by ISBN.
     * @param {string|null} issn    Optional parameter: Filter by ISSN.
     * @param {string|null} issueNumber    Optional parameter: Return only issues in series whose issue number matches the input.
     * @param {string|null} limit    Optional parameter: Limit the result set to the specified number of resources.
     * @param {string|null} modifiedSince    Optional parameter: Return only comics which have been modified since the specified date.
     * @param {string|null} noVariants    Optional parameter: Exclude variants (alternate covers, secondary printings, director's cuts, etc.) from the result set. (Acceptable values are: "true")
     * @param {string|null} offset    Optional parameter: Skip the specified number of resources in the result set.
     * @param {string|null} orderBy    Optional parameter: Order the result set by a field or fields. Add a "-" to the value sort in descending order. Multiple values are given priority in the order in which they are passed. (Acceptable values are: "focDate", "onsaleDate", "title", "issueNumber", "modified", "-focDate", "-onsaleDate", "-title", "-issueNumber", "-modified")
     * @param {string|null} series    Optional parameter: Return only comics which are part of the specified series (accepts a comma-separated list of ids).
     * @param {string|null} sharedAppearances    Optional parameter: Return only comics in which the specified characters appear together (for example in which BOTH Spider-Man and Wolverine appear). Accepts a comma-separated list of ids.
     * @param {string|null} startYear    Optional parameter: Return only issues in series whose start year matches the input.
     * @param {string|null} stories    Optional parameter: Return only comics which contain the specified stories (accepts a comma-separated list of ids).
     * @param {string|null} title    Optional parameter: Return only issues in series whose title matches the input.
     * @param {string|null} titleStartsWith    Optional parameter: Return only issues in series whose title starts with the input.
     * @param {string|null} upc    Optional parameter: Filter by UPC.
     * @param {function} callback    Required parameter: Callback function in the form of function(error, response)
     *
     * @return {ComicDataWrapper}
     */
    getComicsCollection : function(characters, collaborators, creators, dateDescriptor, dateRange, diamondCode, digitalId, ean, events, format, formatType, hasDigitalIssue, isbn, issn, issueNumber, limit, modifiedSince, noVariants, offset, orderBy, series, sharedAppearances, startYear, stories, title, titleStartsWith, upc, callback){

        //prepare query string for API call;
        var _baseUri = _configuration.BASEURI;
        
        var _queryBuilder = _baseUri + "/comics";
        
        //Process query parameters
        _queryBuilder = _APIHelper.appendUrlWithQueryParameters(_queryBuilder, {
            "characters" : characters,
            "collaborators" : collaborators,
            "creators" : creators,
            "dateDescriptor" : (dateDescriptor != null)?dateDescriptor:null,
            "dateRange" : dateRange,
            "diamondCode" : diamondCode,
            "digitalId" : digitalId,
            "ean" : ean,
            "events" : events,
            "format" : format,
            "formatType" : (formatType != null)?formatType:null,
            "hasDigitalIssue" : hasDigitalIssue,
            "isbn" : isbn,
            "issn" : issn,
            "issueNumber" : issueNumber,
            "limit" : limit,
            "modifiedSince" : modifiedSince,
            "noVariants" : noVariants,
            "offset" : offset,
            "orderBy" : orderBy,
            "series" : series,
            "sharedAppearances" : sharedAppearances,
            "startYear" : startYear,
            "stories" : stories,
            "title" : title,
            "titleStartsWith" : titleStartsWith,
            "upc" : upc,
            "apikey" : _configuration.apikey
        });

        //validate and preprocess url
        var _queryUrl = _APIHelper.cleanUrl(_queryBuilder);
        
        //prepare headers
        var _headers = {
            "accept" : "application/json",
            "referer" : _configuration.referer
        };

        //Construct the request
        var _options = {
            queryUrl: _queryUrl,
            method: "GET",
            headers: _headers,
        };
        
        //Build the response processing. 
        function cb(_error, _response, _context) {
            if(_error) {
                callback({errorMessage: _error.message, errorCode: _error.code},null,_context);
            } else if (_response.statusCode >= 200 && _response.statusCode <= 206) {
                callback(null,JSON.parse(_response.body),_context);
            } else if (_response.statusCode == 409) {
                callback({errorMessage: "Limit greater than 100.", errorCode: 409, errorResponse:_response.body},null,_context);
            } else {
                callback({errorMessage: "HTTP Response Not OK", errorCode: _response.statusCode, errorResponse:_response.body},null,_context);
            }
        }
        _request(_options, cb);
    }

};

module.exports = ComicsController;